php:
  build: docker/php
  volumes:
    - ./:/var/www/html/
  links:
    - db
  env_file:
    - .env

nginx:
  build: docker/nginx
  ports:
    - 80:80
  volumes_from:
    - php
  volumes:
    - ./var/logs/nginx/:/var/log/nginx
  links:
    - php

db:
  build: docker/mysql
  ports:
      - "3310:3306"
  environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "test"

db_test:
  build: docker/mysql
  ports:
    - "3311:3306"
  environment:
    MYSQL_DATABASE: "db_test"
    MYSQL_USER: "test"
    MYSQL_PASSWORD: "test"
    MYSQL_ROOT_PASSWORD: "test"