# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  _defaults:
     autowire: true
     autoconfigure: true
     public: true

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
  AppBundle\:
    resource: '../../src/AppBundle/*'
    exclude: '../../src/AppBundle/{Entity,Event,Repository,Tests,Twig}'

  AppBundle\Repository\:
    resource: '../../src/AppBundle/Repository/ClubRepository.php'

  AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        tags: ['controller.service_arguments']

  normalizer.club:
        class: AppBundle\Serializer\Normalizer\ClubNormalizer

  normalizer.tournament:
        class: AppBundle\Serializer\Normalizer\TournamentNormalizer

  normalizer.task:
        class: AppBundle\Serializer\Normalizer\TaskNormalizer

  normalizer.signup:
      class: AppBundle\Serializer\Normalizer\SignUpNormalizer

  normalizer.user:
      class: AppBundle\Serializer\Normalizer\UserNormalizer

  normalizer.fight:
        class: AppBundle\Serializer\Normalizer\FightNormalizer

  serializer.my:
        class: Symfony\Component\Serializer\Serializer
        arguments: [['@normalizer.user', '@normalizer.fight', '@normalizer.signup', '@normalizer.club', '@normalizer.club'], ["@serializer.encoder.json"]]


  app.security.login_form_authenticator:
    class: AppBundle\Security\LoginFormAuthenticator

  app.security.facebook_authenticator:
    class: AppBundle\Security\FacebookAuthenticator

  app.doctrine.hash_password_listener:
    class: AppBundle\Doctrine\HashPasswordListener
    tags:
        - {name: doctrine.event_subscriber}

  app.twig_extension:
          class: AppBundle\Twig\AppExtension
          public: false

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl

  twig.extension.dyting_loader:
    class: Twig_Extension_StringLoader

  cache.kesz:
    class: Symfony\Component\Cache\Simple\FilesystemCache