var classes = [
    {
        "name": "AppBundle\\Controller\\FightController",
        "interface": false,
        "methods": [
            {
                "name": "showAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createFight",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "AppBundle\\Entity\\Fight",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\Fight",
            "AppBundle\\Entity\\Tournament",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\ParamConverter",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\Tournament",
            "AppBundle\\Entity\\Fight",
            "Symfony\\Component\\BrowserKit\\Response",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 2,
        "length": 133,
        "vocabulary": 35,
        "volume": 682.19,
        "difficulty": 6.97,
        "effort": 4753.36,
        "level": 0.14,
        "bugs": 0.23,
        "time": 264,
        "intelligentContent": 97.91,
        "number_operators": 25,
        "number_operands": 108,
        "number_operators_unique": 4,
        "number_operands_unique": 31,
        "cloc": 25,
        "loc": 84,
        "lloc": 59,
        "mi": 78.53,
        "mIwoC": 41.12,
        "commentWeight": 37.4,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 729,
        "relativeDataComplexity": 0.22,
        "relativeSystemComplexity": 729.22,
        "totalStructuralComplexity": 3645,
        "totalDataComplexity": 1.11,
        "totalSystemComplexity": 3646.11,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\TournamentController",
        "interface": false,
        "methods": [
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "showAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "panelAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rulesAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "contactAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\Tournament",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\Tournament",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\Tournament",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\Tournament",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 52,
        "vocabulary": 18,
        "volume": 216.84,
        "difficulty": 4.1,
        "effort": 889.03,
        "level": 0.24,
        "bugs": 0.07,
        "time": 49,
        "intelligentContent": 52.89,
        "number_operators": 11,
        "number_operands": 41,
        "number_operators_unique": 3,
        "number_operands_unique": 15,
        "cloc": 18,
        "loc": 46,
        "lloc": 28,
        "mi": 93.16,
        "mIwoC": 51.94,
        "commentWeight": 41.22,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.73,
        "relativeSystemComplexity": 49.73,
        "totalStructuralComplexity": 245,
        "totalDataComplexity": 3.63,
        "totalSystemComplexity": 248.63,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\ClubController",
        "interface": false,
        "methods": [
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "showAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\Club",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 23,
        "vocabulary": 10,
        "volume": 76.4,
        "difficulty": 2.25,
        "effort": 171.91,
        "level": 0.44,
        "bugs": 0.03,
        "time": 10,
        "intelligentContent": 33.96,
        "number_operators": 5,
        "number_operands": 18,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 9,
        "loc": 24,
        "lloc": 15,
        "mi": 101.66,
        "mIwoC": 61.02,
        "commentWeight": 40.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.36,
        "relativeSystemComplexity": 36.36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.71,
        "totalSystemComplexity": 72.71,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\TQMController",
        "interface": false,
        "methods": [
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "iWillHelpAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\Task",
            "AppBundle\\Entity\\UserTask",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 53,
        "vocabulary": 21,
        "volume": 232.79,
        "difficulty": 3.42,
        "effort": 795.38,
        "level": 0.29,
        "bugs": 0.08,
        "time": 44,
        "intelligentContent": 68.13,
        "number_operators": 12,
        "number_operands": 41,
        "number_operators_unique": 3,
        "number_operands_unique": 18,
        "cloc": 6,
        "loc": 34,
        "lloc": 28,
        "mi": 81.88,
        "mIwoC": 51.59,
        "commentWeight": 30.29,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0.22,
        "relativeSystemComplexity": 225.22,
        "totalStructuralComplexity": 450,
        "totalDataComplexity": 0.44,
        "totalSystemComplexity": 450.44,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\SecurityController",
        "interface": false,
        "methods": [
            {
                "name": "loginAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "registerFBAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "passwordReset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logoutAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setNullOnImageFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 8,
        "ccnMethodMax": 5,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\File\\File",
            "Symfony\\Component\\HttpFoundation\\File\\UploadedFile",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Swift_SmtpTransport",
            "Swift_Mailer",
            "Swift_Message",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Symfony\\Component\\HttpFoundation\\Session\\Session",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 2,
        "length": 259,
        "vocabulary": 70,
        "volume": 1587.48,
        "difficulty": 7.92,
        "effort": 12577.76,
        "level": 0.13,
        "bugs": 0.53,
        "time": 699,
        "intelligentContent": 200.36,
        "number_operators": 53,
        "number_operands": 206,
        "number_operators_unique": 5,
        "number_operands_unique": 65,
        "cloc": 23,
        "loc": 129,
        "lloc": 106,
        "mi": 62.76,
        "mIwoC": 32.33,
        "commentWeight": 30.42,
        "kanDefect": 0.64,
        "relativeStructuralComplexity": 1600,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 1600.2,
        "totalStructuralComplexity": 8000,
        "totalDataComplexity": 1.02,
        "totalSystemComplexity": 8001.02,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\HomepageController",
        "interface": false,
        "methods": [
            {
                "name": "resultAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 26,
        "vocabulary": 14,
        "volume": 98.99,
        "difficulty": 1.75,
        "effort": 173.23,
        "level": 0.57,
        "bugs": 0.03,
        "time": 10,
        "intelligentContent": 56.57,
        "number_operators": 5,
        "number_operands": 21,
        "number_operators_unique": 2,
        "number_operands_unique": 12,
        "cloc": 3,
        "loc": 15,
        "lloc": 12,
        "mi": 94.29,
        "mIwoC": 62.35,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 49.13,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0.13,
        "totalSystemComplexity": 49.13,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\TournamentSignUpController",
        "interface": false,
        "methods": [
            {
                "name": "signUpAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 9,
        "ccnMethodMax": 9,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "AppBundle\\Entity\\Tournament",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\SignUpTournament",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 190,
        "vocabulary": 49,
        "volume": 1066.79,
        "difficulty": 10.47,
        "effort": 11164.13,
        "level": 0.1,
        "bugs": 0.36,
        "time": 620,
        "intelligentContent": 101.94,
        "number_operators": 40,
        "number_operands": 150,
        "number_operators_unique": 6,
        "number_operands_unique": 43,
        "cloc": 6,
        "loc": 66,
        "lloc": 60,
        "mi": 61.31,
        "mIwoC": 38.8,
        "commentWeight": 22.51,
        "kanDefect": 0.87,
        "relativeStructuralComplexity": 900,
        "relativeDataComplexity": 0.19,
        "relativeSystemComplexity": 900.19,
        "totalStructuralComplexity": 900,
        "totalDataComplexity": 0.19,
        "totalSystemComplexity": 900.19,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\Admin\\AdminTournamentFightController",
        "interface": false,
        "methods": [
            {
                "name": "removeFightsWithNotWeighted",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resultAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pairAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setWinnerAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "changeOrderFight",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "publishFights",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toggleFightReady",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setDayAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHighestFormula",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getHighestWeight",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "refreshFightPosition",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 11,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 9,
        "ccnMethodMax": 5,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\Tournament",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\Tournament",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\Tournament",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\Tournament",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\SignUpTournament",
            "AppBundle\\Entity\\SignUpTournament",
            "AppBundle\\Entity\\SignUpTournament",
            "AppBundle\\Entity\\SignUpTournament"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 3,
        "length": 262,
        "vocabulary": 45,
        "volume": 1438.87,
        "difficulty": 13.38,
        "effort": 19244.83,
        "level": 0.07,
        "bugs": 0.48,
        "time": 1069,
        "intelligentContent": 107.58,
        "number_operators": 48,
        "number_operands": 214,
        "number_operators_unique": 5,
        "number_operands_unique": 40,
        "cloc": 31,
        "loc": 144,
        "lloc": 113,
        "mi": 64.82,
        "mIwoC": 31.89,
        "commentWeight": 32.92,
        "kanDefect": 1.07,
        "relativeStructuralComplexity": 729,
        "relativeDataComplexity": 0.4,
        "relativeSystemComplexity": 729.4,
        "totalStructuralComplexity": 8019,
        "totalDataComplexity": 4.43,
        "totalSystemComplexity": 8023.43,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\Admin\\MailController",
        "interface": false,
        "methods": [
            {
                "name": "mailAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 16,
        "loc": 24,
        "lloc": 8,
        "mi": 123.11,
        "mIwoC": 75.43,
        "commentWeight": 47.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\Admin\\AdminTournamentWeight",
        "interface": false,
        "methods": [
            {
                "name": "setWeighted",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 64,
        "vocabulary": 29,
        "volume": 310.91,
        "difficulty": 4.08,
        "effort": 1268.52,
        "level": 0.25,
        "bugs": 0.1,
        "time": 70,
        "intelligentContent": 76.2,
        "number_operators": 13,
        "number_operands": 51,
        "number_operators_unique": 4,
        "number_operands_unique": 25,
        "cloc": 9,
        "loc": 38,
        "lloc": 29,
        "mi": 84.2,
        "mIwoC": 49.97,
        "commentWeight": 34.23,
        "kanDefect": 0.75,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 196.13,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 0.13,
        "totalSystemComplexity": 196.13,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\Admin\\NewsController",
        "interface": false,
        "methods": [
            {
                "name": "indexAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "paginator",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "newAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "showAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createDeleteForm",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteByIdAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "bulkAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method",
            "Pagerfanta\\Adapter\\DoctrineORMAdapter",
            "Pagerfanta\\Pagerfanta",
            "Pagerfanta\\View\\TwitterBootstrap3View",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\News",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method",
            "AppBundle\\Entity\\News",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\News",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\News",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method",
            "AppBundle\\Entity\\News",
            "AppBundle\\Entity\\News",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 252,
        "vocabulary": 56,
        "volume": 1463.45,
        "difficulty": 12.24,
        "effort": 17912.67,
        "level": 0.08,
        "bugs": 0.49,
        "time": 995,
        "intelligentContent": 119.56,
        "number_operators": 48,
        "number_operands": 204,
        "number_operators_unique": 6,
        "number_operands_unique": 50,
        "cloc": 61,
        "loc": 169,
        "lloc": 108,
        "mi": 72.77,
        "mIwoC": 32.67,
        "commentWeight": 40.1,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 841,
        "relativeDataComplexity": 0.44,
        "relativeSystemComplexity": 841.44,
        "totalStructuralComplexity": 7569,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 7573,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\Admin\\UserAdminController",
        "interface": false,
        "methods": [
            {
                "name": "indexAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "newAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "editSignUpTournament",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "AppBundle\\Form\\SignUpTournamentType",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 87,
        "vocabulary": 23,
        "volume": 393.55,
        "difficulty": 7.16,
        "effort": 2816.99,
        "level": 0.14,
        "bugs": 0.13,
        "time": 156,
        "intelligentContent": 54.98,
        "number_operators": 19,
        "number_operands": 68,
        "number_operators_unique": 4,
        "number_operands_unique": 19,
        "cloc": 30,
        "loc": 70,
        "lloc": 41,
        "mi": 88.7,
        "mIwoC": 46.25,
        "commentWeight": 42.45,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 0.35,
        "relativeSystemComplexity": 256.35,
        "totalStructuralComplexity": 1024,
        "totalDataComplexity": 1.41,
        "totalSystemComplexity": 1025.41,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\Admin\\AdminTournamentSignUp",
        "interface": false,
        "methods": [
            {
                "name": "signUp",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toggleReady",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isPaid",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "AppBundle\\Entity\\Tournament",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\SignUpTournament",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\HttpFoundation\\Response",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 79,
        "vocabulary": 24,
        "volume": 362.21,
        "difficulty": 6.3,
        "effort": 2281.94,
        "level": 0.16,
        "bugs": 0.12,
        "time": 127,
        "intelligentContent": 57.49,
        "number_operators": 16,
        "number_operands": 63,
        "number_operators_unique": 4,
        "number_operands_unique": 20,
        "cloc": 16,
        "loc": 52,
        "lloc": 36,
        "mi": 85.6,
        "mIwoC": 47.73,
        "commentWeight": 37.87,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.22,
        "relativeSystemComplexity": 289.22,
        "totalStructuralComplexity": 867,
        "totalDataComplexity": 0.67,
        "totalSystemComplexity": 867.67,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\UserController",
        "interface": false,
        "methods": [
            {
                "name": "listAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "showAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "newAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method",
            "AppBundle\\Entity\\User",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "AppBundle\\Entity\\User",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 70,
        "vocabulary": 25,
        "volume": 325.07,
        "difficulty": 3.95,
        "effort": 1285.5,
        "level": 0.25,
        "bugs": 0.11,
        "time": 71,
        "intelligentContent": 82.2,
        "number_operators": 12,
        "number_operands": 58,
        "number_operators_unique": 3,
        "number_operands_unique": 22,
        "cloc": 18,
        "loc": 47,
        "lloc": 29,
        "mi": 91.16,
        "mIwoC": 50.24,
        "commentWeight": 40.92,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.4,
        "relativeSystemComplexity": 144.4,
        "totalStructuralComplexity": 576,
        "totalDataComplexity": 1.62,
        "totalSystemComplexity": 577.62,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\JustRenderViewController",
        "interface": false,
        "methods": [
            {
                "name": "contactController",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rulesController",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\Fight",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 55,
        "vocabulary": 23,
        "volume": 248.8,
        "difficulty": 3.38,
        "effort": 839.69,
        "level": 0.3,
        "bugs": 0.08,
        "time": 47,
        "intelligentContent": 73.72,
        "number_operators": 10,
        "number_operands": 45,
        "number_operators_unique": 3,
        "number_operands_unique": 20,
        "cloc": 6,
        "loc": 35,
        "lloc": 29,
        "mi": 80.97,
        "mIwoC": 51.05,
        "commentWeight": 29.92,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 361,
        "relativeDataComplexity": 0.18,
        "relativeSystemComplexity": 361.18,
        "totalStructuralComplexity": 722,
        "totalDataComplexity": 0.35,
        "totalSystemComplexity": 722.35,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\FacebookController",
        "interface": false,
        "methods": [
            {
                "name": "connectAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "connectCheckAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\Routing\\Annotation\\Route",
            "Symfony\\Component\\HttpFoundation\\Request",
            "Symfony\\Component\\Routing\\Annotation\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 2,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0.5,
        "effort": 5.8,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 13,
        "loc": 24,
        "lloc": 11,
        "mi": 115.13,
        "mIwoC": 69.69,
        "commentWeight": 45.44,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 9.38,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 18.75,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\CouchController",
        "interface": false,
        "methods": [
            {
                "name": "showFighters",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 14,
        "vocabulary": 9,
        "volume": 44.38,
        "difficulty": 1.57,
        "effort": 69.74,
        "level": 0.64,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 28.24,
        "number_operators": 3,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 6,
        "loc": 16,
        "lloc": 10,
        "mi": 107.15,
        "mIwoC": 66.52,
        "commentWeight": 40.63,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 25.17,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0.17,
        "totalSystemComplexity": 25.17,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AppBundle\\Controller\\Api\\UserController",
        "interface": false,
        "methods": [
            {
                "name": "createAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateAction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Method",
            "Symfony\\Component\\HttpFoundation\\Request",
            "AppBundle\\Entity\\User",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "Symfony\\Component\\HttpFoundation\\JsonResponse",
            "Sensio\\Bundle\\FrameworkExtraBundle\\Configuration\\Route"
        ],
        "parents": [
            "Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller"
        ],
        "lcom": 1,
        "length": 96,
        "vocabulary": 25,
        "volume": 445.81,
        "difficulty": 7.71,
        "effort": 3439.11,
        "level": 0.13,
        "bugs": 0.15,
        "time": 191,
        "intelligentContent": 57.79,
        "number_operators": 15,
        "number_operands": 81,
        "number_operators_unique": 4,
        "number_operands_unique": 21,
        "cloc": 10,
        "loc": 45,
        "lloc": 35,
        "mi": 80.72,
        "mIwoC": 47.36,
        "commentWeight": 33.35,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 256.29,
        "totalStructuralComplexity": 512,
        "totalDataComplexity": 0.59,
        "totalSystemComplexity": 512.59,
        "pageRank": 0.06,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    }
]